[workspace]
members = ["crates/inplace-init", "crates/inplace-init-macros", "examples/showcase"]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
version = "0.1.0"
authors = ["Shao G. <shaog.me@gmail.com>"]
description = "In-place initialization for Rust values, including pinned and field-by-field construction."
repository = "https://github.com/shaogme/inplace-init"
readme = "README.md"
homepage = "https://github.com/shaogme/inplace-init"
documentation = "https://docs.rs/inplace-init"
keywords = ["in-place", "initialization", "pinning", "no-std", "memory"]
categories = ["memory-management", "no-std", "rust-patterns"]

[workspace.dependencies]
inplace-init = { path = "crates/inplace-init" }
inplace-init-macros = { path = "crates/inplace-init-macros", version = "0.1.0" }
