[package]
name = "inplace-init"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme = "README.md"
description.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
default = []
alloc = []
std = ["alloc"]

[dependencies]
inplace-init-macros = { workspace = true, version = "0.1.0" }
