[package]
name = "inplace-init-macros"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
documentation = "https://docs.rs/inplace-init-macros"
description = "Derive and procedural macros for in-place and pinned Rust initialization."
keywords = ["derive", "initialization", "procedural-macro", "macros", "pinning"]
categories = ["development-tools::procedural-macro-helpers"]

[lib]
proc-macro = true

[dependencies]
proc-macro-crate = "3"
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
